Header header

string[] name
int8[] device_id
string[] motor_type
bool[] inverted
int32[] pidf_reference_slot

float64[] p_gain0
float64[] i_gain0
float64[] d_gain0
float64[] f_gain0
float64[] i_zone0
float64[] d_filter0

float64[] p_gain1
float64[] i_gain1
float64[] d_gain1
float64[] f_gain1
float64[] i_zone1
float64[] d_filter1

float64[] p_gain2
float64[] i_gain2
float64[] d_gain2
float64[] f_gain2
float64[] i_zone2
float64[] d_filter2

float64[] p_gain3
float64[] i_gain3
float64[] d_gain3
float64[] f_gain3
float64[] i_zone3
float64[] d_filter3

float64[] pidf_output_min
float64[] pidf_output_max
